config/routes.rb
BeerFlow::Application.routes.draw do

  resources :users, only: [:create, :show]
  get 'signup', to: 'users#new', as: 'new_user'

  resources :questions, only: [:new, :create, :show, :index]
  resources :answers, only: [:create] do
    resources :votes, only: [:create]
  end

  resources :sessions, only: [:create]
  get 'login', to: 'sessions#new', as: 'new_session'
  get 'logout', to: 'sessions#destroy'

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :question_id
  validates_presence_of :body, :question_id
  belongs_to :question
  belongs_to :user
  has_many :votes
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body
  validates_presence_of :title, :body
  has_many :answers
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password_confirmation, :password, :id
  has_secure_password
  has_many :questions
  has_many :answers
  has_many :votes
  validates_presence_of :username, :password_digest, :password_confirmation
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :user_id, :answer_id
  validates_uniqueness_of :user_id, :scope => :answer_id
  belongs_to :user
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer = Answer.new(params[:answer])
    if @answer.save
      render :json => render_to_string(:partial => 'answer', :locals => {:answer => @answer}).to_json
     else
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    @question = Question.new(params[:question])
    @question.save
    redirect_to question_path(@question)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def index
    @questions = Question.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to user_path(@user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(params[:user])
    if @user.valid?
      @user.save
      redirect_to user_path(@user.id)
    else
      redirect_to users_signin_path
    end
  end
# YOU GUYS ARE FUCKED

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def signin
    @user = User.new
  end

  def self.authenticate(params)
    if valid_user?(params[:user][:username], params[:user][:password])
      User.where(username: username).first
    else
      User.create(username: params[:user][:username], password: params[:user][:password] )
    end
  end

   private
  def self.valid_user?(params)
    username = params[:username]
    password = params[:password]
    @user = User.where(username: username).first
    @user.present? && @user.password == password
    # return true
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = Vote.new(user_id: params[:user_id], answer_id: params[:answer_id])
    answer = Answer.find(params[:answer_id])
    vote.save
    redirect_to question_path(answer.question)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    session[:id] ? User.find(session[:id]) : nil
  end

  def log_out
    reset_session
  end

  def log_in(user)
      session[:id] = user.id
  end
end

app/views/answers/_answer.html.erb
<li id="<%=answer.id%>"><%= answer.votes.count %>
<%= button_to "Vote", answer_votes_path(answer, user_id: current_user, answer_id: answer.id) %>
<%= answer.body %>
</li>

app/views/answers/_inline_form.html.erb
<%= form_for(@answer, :remote => true) do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <%= f.hidden_field :question_id, value: @question.id %>
  <%= f.submit "Submit" %>
<% end %>

app/views/answers/show.html.erb
<%= @answer.body %>

app/views/layouts/_inline_navigation.html.erb
<div class="navbar">

	<span class="navigation-actions">
		<%= link_to root_path do %>
			<i class="icon-beer"> BeerOverflow </i>
		<% end %>
	</span>
	<span class="user-actions">
		<% if current_user.nil? %>
		  <%= link_to controller: "sessions", action: "new" do %>
		  	<i class="icon-signin"> Login </i>
		  <% end %>
		  <%= link_to controller: "users", action: "new" do %>
		  	<i class="icon-user"> Sign Up </i>
		  <% end %>
		<% else %>
		  <%= link_to controller: "sessions", action: "destroy" do %>
		  	<i class="icon-signout"> Logout </i>
		  <% end %>
		<% end %>
	</span>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerFlow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>
<body>

<%= render partial: 'layouts/inline_navigation' %>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<ul class="questions-list">
	<% @questions.each do |question| %>
		<li class="question"><%= link_to question.title, question_path(question) %></li>
	<% end %>
</ul>

<%= button_to "New Question", new_question_path, method: :get %>

app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "Submit" %>
<% end %>

app/views/questions/show.html.erb
<%= @question.title %>
<br>
<%= @question.body %>

<ul class="answers">
<% @question.answers.each do|answer| %>
  <br>
  <%= render 'answers/answer', :answer => answer %>
  <br>
<% end %>
</ul>

<%= render partial: 'answers/inline_form' %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
Welcome <%= @user.username %>!

app/views/users/signin.html.erb
<%= form_for @user, url: users_signin_path do |f| %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.text_field :password %>

<%= f.submit "submit" %>

<% end %>

app/views/users/signout.html.erb
Good-bye!
Be sure to check out Fashion Forward!